### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by fenollp** [comment]
I don’t see any changes to the lock file. Is this expected?

**Comment by deadtrickster** [comment]
I think rebar.lock should be updated too.

**Comment by getong** [comment]
I compile it and not  found lock file change .

**Comment by tsloughter** [comment]
No, plugins do not current get locked. So this is correct, just need the cla handled.

**Comment by getong** [comment]
I have no google account, and for some reason, I can not register one in my country.

**Comment by tsloughter** [comment]
@bogdandrutu @mtwo what do we do in this case?

**Comment by tsloughter** [comment]
Closing this since the updates have been made elsewhere at this point.

Thanks again @getong , hopefully we can get this issue figured out so you can contribute more  in the future if you want :)

**Pull request closed without merging**
