### PR TITLE
Add hex.pm badges

### PR DESCRIPTION
**Pull request by deadtrickster**

### CODE REVIEW

**Comment by tsloughter** [comment]
It looks like it is added twice?

**Comment by deadtrickster** [comment]
first shows version, second - downloads count.

**Comment by tsloughter** [comment]
Ooo, `/v/` vs `/d/` :)

**Comment by tsloughter** [comment]
Dammit, ugh, I forgot i can't click the 'update branch' or it breaks google's cla. Sorry, may have to open another PR...

**Pull request closed without merging**
