### PR TITLE
upgrade gpb plugin and oc_trace_pb for otp-21

### PR DESCRIPTION
**Pull request by tsloughter**
Latest gpb creates a `oc_trace_pb` module that compiles properly on 21 as well as versions before 21.

### CODE REVIEW

**Comment by deadtrickster** [comment]
hmm, it's red

**Comment by tsloughter** [comment]
Oh, damn, I misunderstood how Tomas solved this in gpb... I guess it won't work until 21 is released, not positive, but can wait until then to see.

**Comment by tsloughter** [comment]
Hm, confused, doesn't seem to work if running the proto compile with old otp either.

**Comment by tsloughter** [comment]
@deadtrickster nevermind, I wasn't actually recompiling the proto when I thought I was :), it works now.

**Pull request merged**
