### PR TITLE
Mention Prometheus exporter in the readme.

### PR DESCRIPTION
**Pull request by deadtrickster**

### CODE REVIEW

**Comment by tsloughter** [comment]
Have you looked at View at all? I think it might overlap with what this reporter is doing. But I'm really not sure since the only thing in the spec is: https://github.com/census-instrumentation/opencensus-specs#stats :) -- Since I've been working on some grpc stuff, like adding census tracing to grpcbox, I ran into some views code in the other libraries https://github.com/rakyll/opencensus-grpc-demo/blob/master/server/src/main/java/io/grpc/examples/helloworld/GrpcViews.java

I plan to work on tags next, which stats relies on, and then look at stats, but was just thinking there might be some overlap here.

For now the reporter is useful though, so after a rebase we can merge it in.

**Comment by deadtrickster** [comment]
I must admit, I haven't studied existing stats implementation deeply (I know about golang only anyway). But the idea behind this exporter looks a bit different to me. This exporter is not a direct instrumentation, 1) it uses data from spans (_just_ counts and end_time - start_time), 2) you don't have to create measure yourself. And no additional calculations (prometheus does it anyway). Can be extended to map attributes/tags/whatever to labels in a more flexible manner.

**Comment by tsloughter** [comment]
Argh, I tried using the github 'update' branch feature so you didn't have to rebase for it to be able to merge but it seems to not play well with the CLAs...

**Comment by deadtrickster** [comment]
I rebased, github is waiting for cla/google (1h+).

> Note to project maintainer: This is a terminal state, meaning the cla/google commit status will not change from this State. It's up to you to confirm consent of the commit author(s) and merge this pull request when appropriate.

So I guess you can still merge it anyway.

**Comment by tsloughter** [comment]
I can't merge it through github. Maybe the command line instructions will work, assuming I can push directly to master. I'll give that a try in a minute.

**Comment by tsloughter** [comment]
Oh yea, so manual from the cli doesn't work. Can you just create a new PR I guess?

**Pull request closed without merging**
